# Generated by Django 4.0.3 on 2022-06-07 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events_rest', '0002_bookmarkedevent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='picture_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
