stages:
  - test   # Run tests first
  - build  # Run build after tests
  - deploy # Run deploy after build

api-unit-test-job:
  image: python:3-bullseye
  stage: test
  script:
    - cd accounts/api
    - pip install -r requirements.txt
    - python manage.py test  # Run unit tests
    - cd ../../events/api
    - pip install -r requirements.txt
    - python manage.py test  # Run unit tests
    - cd ../../parks/api
    - pip install -r requirements.txt
    - python manage.py test  # Run unit tests

lint-test-job:
  image: python:3-bullseye
  stage: test
  script:
    - pip install flake8
    # Run flake8 on Python project to check for code quality
    - flake8 accounts/api events/api parks/api

build-front-end-job:
  rules:
    # Only run if the commit is on the main branch
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  stage: build
  image: node:lts-bullseye
  needs:
    - api-unit-test-job  # These two jobs must succeed for
    - lint-test-job      # this build-job to run
  script:
    - cd ghi
    - npm install
    - npm run build  # Build the React application
  artifacts:
    paths:
      - ghi/build/  # Save all of the files in the build path

build-back-end-job:
  rules:
    # Only run if the commit is on the main branch
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  stage: build
  image: docker:20.10.16
  services:
    - docker:20.10.16-dind
  script:
    - cd accounts/api
    - docker build -t ${CI_REGISTRY_IMAGE}/accounts:latest .
    - docker tag ${CI_REGISTRY_IMAGE}/accounts:latest ${CI_REGISTRY_IMAGE}/accounts:$CI_JOB_ID
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY
    - docker push ${CI_REGISTRY_IMAGE}/accounts:$CI_JOB_ID
    - docker push ${CI_REGISTRY_IMAGE}/accounts:latest

    - cd ../../events/api
    - docker build -t ${CI_REGISTRY_IMAGE}/events:latest .
    - docker tag ${CI_REGISTRY_IMAGE}/events:latest ${CI_REGISTRY_IMAGE}/events:$CI_JOB_ID
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY
    - docker push ${CI_REGISTRY_IMAGE}/events:$CI_JOB_ID
    - docker push ${CI_REGISTRY_IMAGE}/events:latest

    - cd ../../parks/api
    - docker build -t ${CI_REGISTRY_IMAGE}/parks:latest .
    - docker tag ${CI_REGISTRY_IMAGE}/parks:latest ${CI_REGISTRY_IMAGE}/parks:$CI_JOB_ID
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY
    - docker push ${CI_REGISTRY_IMAGE}/parks:$CI_JOB_ID
    - docker push ${CI_REGISTRY_IMAGE}/parks:latest


deploy-back-end-job-heroku:
  rules:
    # Only run if the commit is on the main branch
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  stage: deploy
  needs:
    - build-back-end-job
  image: docker:20.10.16
  services:
    - docker:20.10.16-dind
  script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY
    - docker login --username=_ --password=$HEROKU_API_KEY registry.heroku.com
    - docker pull $CI_REGISTRY_IMAGE/accounts:latest
    - docker tag ${CI_REGISTRY_IMAGE}/accounts:latest registry.heroku.com/$HEROKU_ACCOUNTS_APP/web:latest
    - docker push registry.heroku.com/$HEROKU_ACCOUNTS_APP/web:latest
    - docker pull $CI_REGISTRY_IMAGE/events:latest
    - docker tag ${CI_REGISTRY_IMAGE}/events:latest registry.heroku.com/$HEROKU_EVENTS_APP/web:latest
    - docker push registry.heroku.com/$HEROKU_EVENTS_APP/web:latest
    - docker pull $CI_REGISTRY_IMAGE/parks:latest
    - docker tag ${CI_REGISTRY_IMAGE}/parks:latest registry.heroku.com/$HEROKU_PARKS_APP/web:latest
    - docker push registry.heroku.com/$HEROKU_PARKS_APP/web:latest

heroku-release:
  stage: deploy
  image: node:10.17-alpine
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  needs:
    - heroku-transfer
  before_script:
    - apk add curl bash
    - curl https://cli-assets.heroku.com/install.sh | sh
  script:
    - heroku container:release web --app $HEROKU_ACCOUNTS_APP
    - heroku container:release web --app $HEROKU_EVENTS_APP
    - heroku container:release web --app $HEROKU_PARKS_APP

# This is an easy way to deploy a React app using GitLab
# Pages. Then, you can access your application from
# gitlab.io.
pages:
  stage: deploy
  rules:
    # Only run if the commit is on the main branch
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  dependencies:
    - build-front-end-job
  needs:
    - build-front-end-job
  script:
    - mv ghi/build public
  artifacts:
    paths:
      public
