# Generated by Django 4.0.3 on 2022-06-23 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("parks_rest", "0002_bookmarkedpark_delete_user_park_state_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bookmarkedpark",
            name="user_id",
            field=models.IntegerField(),
        ),
    ]
