FROM python:3.10-bullseye
ENV PYTHONUNBUFFERED 1
WORKDIR /app
ADD https://github.com/ufoscout/docker-compose-wait/releases/download/2.9.0/wait /wait
RUN chmod +x /wait
COPY requirements.txt requirements.txt
RUN pip install -r requirements.txt
CMD /wait && python manage.py migrate && python manage.py runserver "0.0.0.0:8000"

# FROM python:3.10-bullseye
# RUN python -m pip install --upgrade pip
# WORKDIR /deps
# COPY requirements.txt requirements.txt
# RUN python -m pip install -r requirements.txt
# WORKDIR /app
# CMD uvicorn events_project/asgi:app --reload --host 0.0.0.0
# CMD /wait && python manage.py migrate && python manage.py runserver "0.0.0.0:8000"