# Generated by Django 4.0.3 on 2022-06-07 21:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_rest', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preferences',
            name='user',
            field=models.ManyToManyField(blank=True, null=True, related_name='preferences', to=settings.AUTH_USER_MODEL),
        ),
    ]
