# Generated by Django 4.0.3 on 2022-06-22 22:49

from django.db import migrations

def delete_preferences(apps, schema):
    Preferences = apps.get_model("accounts_rest.Preferences")
    for preference in Preferences.objects.all():
        preference.delete()


def insert_preferences(apps,schema):
    Preferences = apps.get_model("accounts_rest.Preferences")
    Preferences.objects.get_or_create(name="Parks")
    Preferences.objects.get_or_create(name="Hiking")
    Preferences.objects.get_or_create(name="Kayaking")
    Preferences.objects.get_or_create(name="Sailing")
    Preferences.objects.get_or_create(name="Camping")
    Preferences.objects.get_or_create(name="Museum Exhibits")
    Preferences.objects.get_or_create(name="Arts and Culture")
    Preferences.objects.get_or_create(name="Theater")
    Preferences.objects.get_or_create(name="Sports")
    Preferences.objects.get_or_create(name="Concerts")
    Preferences.objects.get_or_create(name="Water Activities")
    Preferences.objects.get_or_create(name="Trails")
   


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_rest', '0002_alter_preferences_user'),
    ]

    operations = [
        migrations.RunPython(insert_preferences,delete_preferences)
    ]
